name: Test Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install deps
      run: cd app && yarn
    - name: Run ESLint
      run: cd app && yarn eslint:frontend && yarn eslint:backend
    - name: Run stylelint
      run: cd app && yarn stylelint:frontend
    - name: Build project
      run: cd app && nx run-many --target=build --parallel
